version: "3"
services:

  db:
    image: ankane/pgvector
    environment:
      POSTGRES_PASSWORD: password
      PGPASSWORD: password


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - PMA_PASSWORD=${DB_PASSWORD-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD-password}
      - MYSQL_PASSWORD=${DB_PASSWORD-password}
      - PMA_HOST=db:3306
      - PMA_ABSOLUTE_URI=https://admin.db.137.120.31.102.nip.io
      - VIRTUAL_HOST=admin.db.137.120.31.102.nip.io
      - LETSENCRYPT_HOST=admin.db.137.120.31.102.nip.io
      - VIRTUAL_PORT=80



  qdrant:
    # https://hub.docker.com/r/qdrant/qdrant/tags
    image: qdrant/qdrant:v1.7.3
    restart: unless-stopped
    volumes:
      - ./data/qdrant:/qdrant/storage
      # - ./scripts/qdrant_config.yml:/qdrant/config/production.yaml
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true
      # - VIRTUAL_HOST=qdrant.blah.137.120.31.148.nip.io
      - VIRTUAL_HOST=qdrant.blah.137.120.31.102.nip.io
      - LETSENCRYPT_HOST=qdrant.blah.137.120.31.102.nip.io
      - VIRTUAL_PORT=6333
    # ports:
    #   - 6333:6333
    #   - 6334:6334
    # command:
    #   - ./qdrant --config-path /qdrant/qdrant_config.yml/home/vemonet/dev/llm/libre-chat/scripts/qdrant_config.yml

  workspace:
    build: .
    volumes:
      - .:/app
