version: "3"
services:

  qdrant:
    # https://hub.docker.com/r/qdrant/qdrant/tags
    image: qdrant/qdrant:v1.7.3
    restart: unless-stopped
    volumes:
      - ./data/qdrant:/qdrant/storage
      # - ./scripts/qdrant_config.yml:/qdrant/config/production.yaml
    environment:
      - QDRANT_ALLOW_RECOVERY_MODE=true
      # - VIRTUAL_HOST=qdrant.blah.137.120.31.148.nip.io
      - VIRTUAL_HOST=qdrant.blah.137.120.31.102.nip.io
      - LETSENCRYPT_HOST=qdrant.blah.137.120.31.102.nip.io
      - VIRTUAL_PORT=6333
    # ports:
    #   - 6333:6333
    #   - 6334:6334
    # command:
    #   - ./qdrant --config-path /qdrant/qdrant_config.yml/home/vemonet/dev/llm/libre-chat/scripts/qdrant_config.yml

  workspace:
    build: .
    volumes:
      - .:/app
